[package]
name = "cedfs-proto"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true }
derive_builder = { workspace = true }
iota = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }

axum = { version = "0.8", features = ["multipart"], optional = true }
axum-server = { version = "0.6", features = ["tls-rustls"] }

[build-dependencies]
tonic-build = { workspace = true }
