// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAttrRequest {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAttrResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDirRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDirResponse {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<DirEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupRequest {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookupResponse {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint64, tag = "3")]
    pub buf_size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadResponse {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub blocks_pos: ::core::option::Option<BlocksPos>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAttrRequest {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAttrResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint64, tag = "3")]
    pub buf_size: u64,
    #[prost(uint64, tag = "4")]
    pub file_length: u64,
    #[prost(uint64, tag = "5")]
    pub replica_num: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteResponse {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "3")]
    pub blocks_pos: ::core::option::Option<BlocksPos>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirEntry {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockEntry {
    #[prost(string, tag = "1")]
    pub datanode_ip: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub bid: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockPos {
    #[prost(string, tag = "1")]
    pub datanode_ip: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub block_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlocksPos {
    #[prost(message, repeated, tag = "1")]
    pub blocks_pos: ::prost::alloc::vec::Vec<BlockPos>,
    #[prost(message, repeated, tag = "2")]
    pub replica_blocks_pos: ::prost::alloc::vec::Vec<ReplicaBlocks>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicaBlocks {
    #[prost(message, repeated, tag = "1")]
    pub replica_blocks: ::prost::alloc::vec::Vec<BlockPos>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
    #[prost(uint32, tag = "4")]
    pub mode: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateResponse {
    #[prost(uint64, tag = "1")]
    pub ino: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveFileRequest {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MoveFileResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlinkRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlinkResponse {
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub blocks: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CopyFileRequest {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CopyFileResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
    #[prost(bytes = "vec", tag = "4")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub blocks: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LinkResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteResponse {}
/// / FIXME: Delete it
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAttrByPathRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
/// / FIXME: Delete it
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAttrByPathResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
/// / FIXME: Delete it
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAttrByPathRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub set_attr: ::prost::alloc::vec::Vec<u8>,
}
/// / FIXME: Delete it
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAttrByPathResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub attr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CopyReplicaRequest {
    #[prost(uint64, tag = "1")]
    pub first_block: u64,
    #[prost(uint64, tag = "2")]
    pub last_block: u64,
    #[prost(message, optional, tag = "3")]
    pub blocks_pos: ::core::option::Option<BlocksPos>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CopyReplicaResponse {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllNodeIpsRequest {
    /// Optional filter by server type (Meta, Data)
    #[prost(string, optional, tag = "1")]
    pub server_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional filter by layer (Cloud, Edge, Device)
    #[prost(string, optional, tag = "2")]
    pub layer: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeInfo {
    /// Node IP address
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    /// Node port
    #[prost(uint32, tag = "2")]
    pub port: u32,
    /// Server type (Meta, Data)
    #[prost(string, tag = "3")]
    pub server_type: ::prost::alloc::string::String,
    /// Layer (Cloud, Edge, Device)
    #[prost(string, tag = "4")]
    pub layer: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllNodeIpsResponse {
    /// List of nodes with type information
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<NodeInfo>,
}
/// No parameters needed - gets usage for the current physical host
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetUsageRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetUsageResponse {
    /// Total disk space in bytes
    #[prost(uint64, tag = "1")]
    pub total_space: u64,
    /// Used disk space in bytes
    #[prost(uint64, tag = "2")]
    pub used_space: u64,
    /// Available disk space in bytes
    #[prost(uint64, tag = "3")]
    pub available_space: u64,
    /// Usage percentage (0.0 to 100.0)
    #[prost(double, tag = "4")]
    pub usage_percentage: f64,
}
/// Generated client implementations.
pub mod client2_meta_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct Client2MetaClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl Client2MetaClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> Client2MetaClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> Client2MetaClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            Client2MetaClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_attr(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAttrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/GetAttr",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "GetAttr"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_dir(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDirRequest>,
        ) -> std::result::Result<tonic::Response<super::GetDirResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/GetDir",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "GetDir"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn lookup(
            &mut self,
            request: impl tonic::IntoRequest<super::LookupRequest>,
        ) -> std::result::Result<tonic::Response<super::LookupResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Lookup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Lookup"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn read(
            &mut self,
            request: impl tonic::IntoRequest<super::ReadRequest>,
        ) -> std::result::Result<tonic::Response<super::ReadResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Read",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Read"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_attr(
            &mut self,
            request: impl tonic::IntoRequest<super::SetAttrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetAttrResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/SetAttr",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "SetAttr"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn write(
            &mut self,
            request: impl tonic::IntoRequest<super::WriteRequest>,
        ) -> std::result::Result<tonic::Response<super::WriteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Write",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Write"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn create(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::CreateResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Create",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Create"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn move_file(
            &mut self,
            request: impl tonic::IntoRequest<super::MoveFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MoveFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/MoveFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "MoveFile"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn unlink(
            &mut self,
            request: impl tonic::IntoRequest<super::UnlinkRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlinkResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Unlink",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Unlink"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn copy_file(
            &mut self,
            request: impl tonic::IntoRequest<super::CopyFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CopyFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/CopyFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "CopyFile"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn link(
            &mut self,
            request: impl tonic::IntoRequest<super::LinkRequest>,
        ) -> std::result::Result<tonic::Response<super::LinkResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Link",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Link"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/Delete",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "Delete"));
            self.inner.unary(req, path, codec).await
        }
        ///    rpc CreateNodeReplica(CreateNodeReplicaRequest) returns (CreateNodeReplicaResponse);
        ///    rpc DeleteNodeReplica(DeleteNodeReplicaRequest) returns (DeleteNodeReplicaResponse);
        ///    rpc MoveNodeReplica(MoveNodeReplicaRequest) returns (MoveNodeReplicaResponse);
        pub async fn copy_replica(
            &mut self,
            request: impl tonic::IntoRequest<super::CopyReplicaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CopyReplicaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/CopyReplica",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "CopyReplica"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_all_node_ips(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAllNodeIpsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAllNodeIpsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/GetAllNodeIps",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "GetAllNodeIps"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_usage(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUsageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUsageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/GetUsage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "GetUsage"));
            self.inner.unary(req, path, codec).await
        }
        /// / FIXME: Delete it
        pub async fn get_attr_by_path(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAttrByPathRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrByPathResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/GetAttrByPath",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "GetAttrByPath"));
            self.inner.unary(req, path, codec).await
        }
        /// / FIXME: Delete it
        pub async fn set_attr_by_path(
            &mut self,
            request: impl tonic::IntoRequest<super::SetAttrByPathRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetAttrByPathResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/client2meta.Client2Meta/SetAttrByPath",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("client2meta.Client2Meta", "SetAttrByPath"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod client2_meta_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with Client2MetaServer.
    #[async_trait]
    pub trait Client2Meta: std::marker::Send + std::marker::Sync + 'static {
        async fn get_attr(
            &self,
            request: tonic::Request<super::GetAttrRequest>,
        ) -> std::result::Result<tonic::Response<super::GetAttrResponse>, tonic::Status>;
        async fn get_dir(
            &self,
            request: tonic::Request<super::GetDirRequest>,
        ) -> std::result::Result<tonic::Response<super::GetDirResponse>, tonic::Status>;
        async fn lookup(
            &self,
            request: tonic::Request<super::LookupRequest>,
        ) -> std::result::Result<tonic::Response<super::LookupResponse>, tonic::Status>;
        async fn read(
            &self,
            request: tonic::Request<super::ReadRequest>,
        ) -> std::result::Result<tonic::Response<super::ReadResponse>, tonic::Status>;
        async fn set_attr(
            &self,
            request: tonic::Request<super::SetAttrRequest>,
        ) -> std::result::Result<tonic::Response<super::SetAttrResponse>, tonic::Status>;
        async fn write(
            &self,
            request: tonic::Request<super::WriteRequest>,
        ) -> std::result::Result<tonic::Response<super::WriteResponse>, tonic::Status>;
        async fn create(
            &self,
            request: tonic::Request<super::CreateRequest>,
        ) -> std::result::Result<tonic::Response<super::CreateResponse>, tonic::Status>;
        async fn move_file(
            &self,
            request: tonic::Request<super::MoveFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MoveFileResponse>,
            tonic::Status,
        >;
        async fn unlink(
            &self,
            request: tonic::Request<super::UnlinkRequest>,
        ) -> std::result::Result<tonic::Response<super::UnlinkResponse>, tonic::Status>;
        async fn copy_file(
            &self,
            request: tonic::Request<super::CopyFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CopyFileResponse>,
            tonic::Status,
        >;
        async fn link(
            &self,
            request: tonic::Request<super::LinkRequest>,
        ) -> std::result::Result<tonic::Response<super::LinkResponse>, tonic::Status>;
        async fn delete(
            &self,
            request: tonic::Request<super::DeleteRequest>,
        ) -> std::result::Result<tonic::Response<super::DeleteResponse>, tonic::Status>;
        ///    rpc CreateNodeReplica(CreateNodeReplicaRequest) returns (CreateNodeReplicaResponse);
        ///    rpc DeleteNodeReplica(DeleteNodeReplicaRequest) returns (DeleteNodeReplicaResponse);
        ///    rpc MoveNodeReplica(MoveNodeReplicaRequest) returns (MoveNodeReplicaResponse);
        async fn copy_replica(
            &self,
            request: tonic::Request<super::CopyReplicaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CopyReplicaResponse>,
            tonic::Status,
        >;
        async fn get_all_node_ips(
            &self,
            request: tonic::Request<super::GetAllNodeIpsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAllNodeIpsResponse>,
            tonic::Status,
        >;
        async fn get_usage(
            &self,
            request: tonic::Request<super::GetUsageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUsageResponse>,
            tonic::Status,
        >;
        /// / FIXME: Delete it
        async fn get_attr_by_path(
            &self,
            request: tonic::Request<super::GetAttrByPathRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAttrByPathResponse>,
            tonic::Status,
        >;
        /// / FIXME: Delete it
        async fn set_attr_by_path(
            &self,
            request: tonic::Request<super::SetAttrByPathRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetAttrByPathResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct Client2MetaServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> Client2MetaServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for Client2MetaServer<T>
    where
        T: Client2Meta,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/client2meta.Client2Meta/GetAttr" => {
                    #[allow(non_camel_case_types)]
                    struct GetAttrSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::GetAttrRequest>
                    for GetAttrSvc<T> {
                        type Response = super::GetAttrResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAttrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::get_attr(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAttrSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/GetDir" => {
                    #[allow(non_camel_case_types)]
                    struct GetDirSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::GetDirRequest>
                    for GetDirSvc<T> {
                        type Response = super::GetDirResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDirRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::get_dir(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDirSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Lookup" => {
                    #[allow(non_camel_case_types)]
                    struct LookupSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::LookupRequest>
                    for LookupSvc<T> {
                        type Response = super::LookupResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LookupRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::lookup(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LookupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Read" => {
                    #[allow(non_camel_case_types)]
                    struct ReadSvc<T: Client2Meta>(pub Arc<T>);
                    impl<T: Client2Meta> tonic::server::UnaryService<super::ReadRequest>
                    for ReadSvc<T> {
                        type Response = super::ReadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/SetAttr" => {
                    #[allow(non_camel_case_types)]
                    struct SetAttrSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::SetAttrRequest>
                    for SetAttrSvc<T> {
                        type Response = super::SetAttrResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetAttrRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::set_attr(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetAttrSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Write" => {
                    #[allow(non_camel_case_types)]
                    struct WriteSvc<T: Client2Meta>(pub Arc<T>);
                    impl<T: Client2Meta> tonic::server::UnaryService<super::WriteRequest>
                    for WriteSvc<T> {
                        type Response = super::WriteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WriteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::write(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WriteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Create" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::CreateRequest>
                    for CreateSvc<T> {
                        type Response = super::CreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/MoveFile" => {
                    #[allow(non_camel_case_types)]
                    struct MoveFileSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::MoveFileRequest>
                    for MoveFileSvc<T> {
                        type Response = super::MoveFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MoveFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::move_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MoveFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Unlink" => {
                    #[allow(non_camel_case_types)]
                    struct UnlinkSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::UnlinkRequest>
                    for UnlinkSvc<T> {
                        type Response = super::UnlinkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnlinkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::unlink(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnlinkSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/CopyFile" => {
                    #[allow(non_camel_case_types)]
                    struct CopyFileSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::CopyFileRequest>
                    for CopyFileSvc<T> {
                        type Response = super::CopyFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CopyFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::copy_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CopyFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Link" => {
                    #[allow(non_camel_case_types)]
                    struct LinkSvc<T: Client2Meta>(pub Arc<T>);
                    impl<T: Client2Meta> tonic::server::UnaryService<super::LinkRequest>
                    for LinkSvc<T> {
                        type Response = super::LinkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LinkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::link(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LinkSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/Delete" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::DeleteRequest>
                    for DeleteSvc<T> {
                        type Response = super::DeleteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::delete(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/CopyReplica" => {
                    #[allow(non_camel_case_types)]
                    struct CopyReplicaSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::CopyReplicaRequest>
                    for CopyReplicaSvc<T> {
                        type Response = super::CopyReplicaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CopyReplicaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::copy_replica(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CopyReplicaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/GetAllNodeIps" => {
                    #[allow(non_camel_case_types)]
                    struct GetAllNodeIpsSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::GetAllNodeIpsRequest>
                    for GetAllNodeIpsSvc<T> {
                        type Response = super::GetAllNodeIpsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAllNodeIpsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::get_all_node_ips(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAllNodeIpsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/GetUsage" => {
                    #[allow(non_camel_case_types)]
                    struct GetUsageSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::GetUsageRequest>
                    for GetUsageSvc<T> {
                        type Response = super::GetUsageResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUsageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::get_usage(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUsageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/GetAttrByPath" => {
                    #[allow(non_camel_case_types)]
                    struct GetAttrByPathSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::GetAttrByPathRequest>
                    for GetAttrByPathSvc<T> {
                        type Response = super::GetAttrByPathResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAttrByPathRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::get_attr_by_path(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAttrByPathSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/client2meta.Client2Meta/SetAttrByPath" => {
                    #[allow(non_camel_case_types)]
                    struct SetAttrByPathSvc<T: Client2Meta>(pub Arc<T>);
                    impl<
                        T: Client2Meta,
                    > tonic::server::UnaryService<super::SetAttrByPathRequest>
                    for SetAttrByPathSvc<T> {
                        type Response = super::SetAttrByPathResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetAttrByPathRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Client2Meta>::set_attr_by_path(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetAttrByPathSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for Client2MetaServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "client2meta.Client2Meta";
    impl<T> tonic::server::NamedService for Client2MetaServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
