// This file is @generated by prost-build.
/// 数据服务器信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataServer {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    /// IP地址（字符串形式）
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    /// http端口
    #[prost(uint32, tag = "3")]
    pub http_port: u32,
    /// rpc端口
    #[prost(uint32, tag = "4")]
    pub rpc_port: u32,
    /// 模型名称
    #[prost(string, tag = "5")]
    pub model_name: ::prost::alloc::string::String,
    /// 实例url
    #[prost(string, tag = "6")]
    pub url: ::prost::alloc::string::String,
}
/// 元数据服务器信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaServer {
    /// IP地址（字符串形式）
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    /// 端口
    #[prost(uint32, tag = "2")]
    pub port: u32,
    /// 网络层级
    #[prost(uint32, tag = "3")]
    pub layer: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KvBlockMeta {
    /// 块哈希：固定长度 32 字节
    #[prost(bytes = "vec", tag = "1")]
    pub token_hash: ::prost::alloc::vec::Vec<u8>,
    /// 下一个 token 的 32 字节哈希列表
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub next_tokens: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// 副本信息
    #[prost(uint32, repeated, tag = "3")]
    pub server_id: ::prost::alloc::vec::Vec<u32>,
}
/// 本地单个 block 的引用计数
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalBlockCount {
    /// 块哈希：固定长度 32 字节
    #[prost(bytes = "vec", tag = "1")]
    pub token_hash: ::prost::alloc::vec::Vec<u8>,
    /// 引用计数（定期同步时为增量计数，启动同步时为全量计数）
    #[prost(uint64, tag = "2")]
    pub count: u64,
}
/// 更新kvmeta的操作方式（创建、删除副本时）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateKvOp {
    /// 块哈希：固定长度 32 字节
    #[prost(bytes = "vec", tag = "1")]
    pub token_hash: ::prost::alloc::vec::Vec<u8>,
    /// server_id的修改方式（1为增加，2为删除）
    #[prost(uint32, tag = "2")]
    pub operation: u32,
    /// server_id
    #[prost(uint32, tag = "3")]
    pub server_id: u32,
}
/// 分块的token信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenLists {
    /// token ids
    #[prost(uint32, repeated, tag = "1")]
    pub tokens: ::prost::alloc::vec::Vec<u32>,
}
/// kvcache位置信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KvBlockPos {
    /// 模型名称
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    /// 推理实例的服务url
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    /// 匹配的kvcache长度
    #[prost(uint32, tag = "3")]
    pub len: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResult {
    /// 单个请求的kv cache搜索结果
    #[prost(message, repeated, tag = "1")]
    pub block_pos: ::prost::alloc::vec::Vec<KvBlockPos>,
}
/// 1.数据服务器向元数据服务器上传本地新增kvcache元数据
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadKvMetaRequest {
    #[prost(uint32, tag = "1")]
    pub server_id: u32,
    #[prost(uint32, repeated, tag = "2")]
    pub tokens: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UploadKvMetaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 2.数据服务器向元数据服务器注册推理实例信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterInstanceRequest {
    #[prost(message, optional, tag = "1")]
    pub data_server: ::core::option::Option<DataServer>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisterInstanceResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 3.数据服务器向元数据服务器上传本地删除kvcache元数据
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveKvMetaRequest {
    #[prost(int32, tag = "1")]
    pub remove_nums: i32,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub tokens_hash: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveKvMetaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 1. GetKvMeta - 获取副本列表
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKvMetaRequest {
    /// 本地节点的元数据服务器信息
    #[prost(message, optional, tag = "1")]
    pub meta_server: ::core::option::Option<MetaServer>,
    /// 本地节点的数据服务器信息
    #[prost(message, repeated, tag = "2")]
    pub data_server: ::prost::alloc::vec::Vec<DataServer>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKvMetaResponse {
    /// 副本信息列表
    #[prost(message, repeated, tag = "1")]
    pub meta: ::prost::alloc::vec::Vec<KvBlockMeta>,
    /// 目标节点已知的元数据服务器信息
    #[prost(message, repeated, tag = "2")]
    pub meta_server: ::prost::alloc::vec::Vec<MetaServer>,
    /// 目标节点已知的数据服务器信息
    #[prost(message, repeated, tag = "3")]
    pub data_server: ::prost::alloc::vec::Vec<DataServer>,
    /// 本地所有 block 的全量计数
    #[prost(message, repeated, tag = "4")]
    pub local_counts: ::prost::alloc::vec::Vec<LocalBlockCount>,
}
/// 2. UpdateKvMeta - 更新kvcache元数据
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateKvMetaRequest {
    /// 本地新的kvcache元数据
    #[prost(message, repeated, tag = "1")]
    pub meta: ::prost::alloc::vec::Vec<KvBlockMeta>,
    /// 本地所有 block 的增量计数
    #[prost(message, repeated, tag = "2")]
    pub local_counts: ::prost::alloc::vec::Vec<LocalBlockCount>,
    /// 创建、删除KV Cache副本
    #[prost(message, repeated, tag = "3")]
    pub update_op: ::prost::alloc::vec::Vec<UpdateKvOp>,
    /// 本地快照的时间戳
    #[prost(uint64, tag = "4")]
    pub update_time: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateKvMetaResponse {
    /// 目标节点已知的元数据服务器信息
    #[prost(message, repeated, tag = "1")]
    pub meta_server: ::prost::alloc::vec::Vec<MetaServer>,
    /// 目标节点已知的数据服务器信息
    #[prost(message, repeated, tag = "2")]
    pub data_server: ::prost::alloc::vec::Vec<DataServer>,
}
/// 3. SearchKvBlock - 根据token查找kvblock
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchKvBlockRequest {
    #[prost(message, repeated, tag = "1")]
    pub query_lists: ::prost::alloc::vec::Vec<TokenLists>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchKvBlockResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SearchResult>,
}
/// 4. SearchKvBlockByPrompts - 根据prompts查找kvblock
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchKvBlockByPromptsRequest {
    #[prost(string, repeated, tag = "1")]
    pub model_name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub prompts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchKvBlockByPromptsResponse {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SearchResult>,
}
/// Generated client implementations.
pub mod kv_meta2_data_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct KvMeta2DataClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl KvMeta2DataClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> KvMeta2DataClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> KvMeta2DataClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            KvMeta2DataClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn upload_kv_meta(
            &mut self,
            request: impl tonic::IntoRequest<super::UploadKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UploadKvMetaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Data/UploadKvMeta",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Data", "UploadKvMeta"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn register_instance(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterInstanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterInstanceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Data/RegisterInstance",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Data", "RegisterInstance"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn remove_kv_meta(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveKvMetaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Data/RemoveKvMeta",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Data", "RemoveKvMeta"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod kv_meta2_meta_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct KvMeta2MetaClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl KvMeta2MetaClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> KvMeta2MetaClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> KvMeta2MetaClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            KvMeta2MetaClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_kv_meta(
            &mut self,
            request: impl tonic::IntoRequest<super::GetKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKvMetaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Meta/GetKvMeta",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Meta", "GetKvMeta"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_kv_meta(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateKvMetaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Meta/UpdateKvMeta",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Meta", "UpdateKvMeta"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_kv_block(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchKvBlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchKvBlockResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Meta/SearchKvBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("kvcache.KvMeta2Meta", "SearchKvBlock"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_kv_block_by_prompts(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchKvBlockByPromptsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchKvBlockByPromptsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/kvcache.KvMeta2Meta/SearchKvBlockByPrompts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("kvcache.KvMeta2Meta", "SearchKvBlockByPrompts"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod kv_meta2_data_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with KvMeta2DataServer.
    #[async_trait]
    pub trait KvMeta2Data: std::marker::Send + std::marker::Sync + 'static {
        async fn upload_kv_meta(
            &self,
            request: tonic::Request<super::UploadKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UploadKvMetaResponse>,
            tonic::Status,
        >;
        async fn register_instance(
            &self,
            request: tonic::Request<super::RegisterInstanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterInstanceResponse>,
            tonic::Status,
        >;
        async fn remove_kv_meta(
            &self,
            request: tonic::Request<super::RemoveKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveKvMetaResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct KvMeta2DataServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> KvMeta2DataServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for KvMeta2DataServer<T>
    where
        T: KvMeta2Data,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/kvcache.KvMeta2Data/UploadKvMeta" => {
                    #[allow(non_camel_case_types)]
                    struct UploadKvMetaSvc<T: KvMeta2Data>(pub Arc<T>);
                    impl<
                        T: KvMeta2Data,
                    > tonic::server::UnaryService<super::UploadKvMetaRequest>
                    for UploadKvMetaSvc<T> {
                        type Response = super::UploadKvMetaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UploadKvMetaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Data>::upload_kv_meta(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UploadKvMetaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/kvcache.KvMeta2Data/RegisterInstance" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterInstanceSvc<T: KvMeta2Data>(pub Arc<T>);
                    impl<
                        T: KvMeta2Data,
                    > tonic::server::UnaryService<super::RegisterInstanceRequest>
                    for RegisterInstanceSvc<T> {
                        type Response = super::RegisterInstanceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterInstanceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Data>::register_instance(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterInstanceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/kvcache.KvMeta2Data/RemoveKvMeta" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveKvMetaSvc<T: KvMeta2Data>(pub Arc<T>);
                    impl<
                        T: KvMeta2Data,
                    > tonic::server::UnaryService<super::RemoveKvMetaRequest>
                    for RemoveKvMetaSvc<T> {
                        type Response = super::RemoveKvMetaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveKvMetaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Data>::remove_kv_meta(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveKvMetaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for KvMeta2DataServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "kvcache.KvMeta2Data";
    impl<T> tonic::server::NamedService for KvMeta2DataServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated server implementations.
pub mod kv_meta2_meta_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with KvMeta2MetaServer.
    #[async_trait]
    pub trait KvMeta2Meta: std::marker::Send + std::marker::Sync + 'static {
        async fn get_kv_meta(
            &self,
            request: tonic::Request<super::GetKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKvMetaResponse>,
            tonic::Status,
        >;
        async fn update_kv_meta(
            &self,
            request: tonic::Request<super::UpdateKvMetaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateKvMetaResponse>,
            tonic::Status,
        >;
        async fn search_kv_block(
            &self,
            request: tonic::Request<super::SearchKvBlockRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchKvBlockResponse>,
            tonic::Status,
        >;
        async fn search_kv_block_by_prompts(
            &self,
            request: tonic::Request<super::SearchKvBlockByPromptsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchKvBlockByPromptsResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct KvMeta2MetaServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> KvMeta2MetaServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for KvMeta2MetaServer<T>
    where
        T: KvMeta2Meta,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/kvcache.KvMeta2Meta/GetKvMeta" => {
                    #[allow(non_camel_case_types)]
                    struct GetKvMetaSvc<T: KvMeta2Meta>(pub Arc<T>);
                    impl<
                        T: KvMeta2Meta,
                    > tonic::server::UnaryService<super::GetKvMetaRequest>
                    for GetKvMetaSvc<T> {
                        type Response = super::GetKvMetaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetKvMetaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Meta>::get_kv_meta(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetKvMetaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/kvcache.KvMeta2Meta/UpdateKvMeta" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateKvMetaSvc<T: KvMeta2Meta>(pub Arc<T>);
                    impl<
                        T: KvMeta2Meta,
                    > tonic::server::UnaryService<super::UpdateKvMetaRequest>
                    for UpdateKvMetaSvc<T> {
                        type Response = super::UpdateKvMetaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateKvMetaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Meta>::update_kv_meta(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateKvMetaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/kvcache.KvMeta2Meta/SearchKvBlock" => {
                    #[allow(non_camel_case_types)]
                    struct SearchKvBlockSvc<T: KvMeta2Meta>(pub Arc<T>);
                    impl<
                        T: KvMeta2Meta,
                    > tonic::server::UnaryService<super::SearchKvBlockRequest>
                    for SearchKvBlockSvc<T> {
                        type Response = super::SearchKvBlockResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SearchKvBlockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Meta>::search_kv_block(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchKvBlockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/kvcache.KvMeta2Meta/SearchKvBlockByPrompts" => {
                    #[allow(non_camel_case_types)]
                    struct SearchKvBlockByPromptsSvc<T: KvMeta2Meta>(pub Arc<T>);
                    impl<
                        T: KvMeta2Meta,
                    > tonic::server::UnaryService<super::SearchKvBlockByPromptsRequest>
                    for SearchKvBlockByPromptsSvc<T> {
                        type Response = super::SearchKvBlockByPromptsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SearchKvBlockByPromptsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as KvMeta2Meta>::search_kv_block_by_prompts(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchKvBlockByPromptsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for KvMeta2MetaServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "kvcache.KvMeta2Meta";
    impl<T> tonic::server::NamedService for KvMeta2MetaServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
