syntax = "proto3";

package client2data;

service Client2Data {
    rpc WriteBlock(WriteBlockRequest) returns (WriteBlockResponse);
    rpc ReadBlock(ReadBlockRequest) returns (ReadBlockResponse);
}

message WriteBlockRequest {
    int64 bid = 1;
    uint64 offset = 2;
}

message WriteBlockResponse {
    bytes cert = 1;
    string quinn_addr = 2;
    string quinn_name = 3;
}

message ReadBlockRequest {
    int64 bid = 1;
    uint64 offset = 2;
    uint64 size = 3;
}

message ReadBlockResponse {
    bytes cert = 1;
    string quinn_addr = 2;
    string quinn_name = 3;
}
