syntax = "proto3";

package data2data;

service Data2Data {
    rpc SendData(SendDataRequest) returns (SendDataResponse);
    rpc GetNodeInfo(GetNodeInfoRequest) returns (GetNodeInfoResponse);
}

message SendDataRequest {
    int64 bid = 1;
}

message SendDataResponse {
    bytes cert = 1;
    string quinn_addr = 2;
    string quinn_name = 3;
}

message GetNodeInfoRequest {
}

message GetNodeInfoResponse {
    uint64 available_memory = 1;
    uint64 available_memory_ratio = 2;
    uint64 available_disk = 3;
    uint64 available_disk_ratio = 4;
}
