syntax = "proto3";

package kvcache;

service KvMeta2Meta {
    rpc GetKvMeta(GetKvMetaRequest) returns (GetKvMetaResponse);
    rpc UpdateKvMeta(UpdateKvMetaRequest) returns (UpdateKvMetaResponse);
}

// 数据服务器信息
message DataServer {
    uint32 id = 1;         
    string ip = 2;                      // IP地址（字符串形式）
    uint32 http_port = 3;               // http端口
    uint32 rpc_port = 4;                // rpc端口
    uint32 layer = 5;                   // 网络层级
    repeated string instance = 6;       // 实例类型
}

// 元数据服务器信息
message MetaServer {
    string ip = 1;                      // IP地址（字符串形式）
    uint32 port = 2;                    // 端口
    uint32 layer = 3;                   // 网络层级
}

message KvBlockMeta {
    uint64 block_id = 1;                // 块 ID  
    uint64 token_hash = 2;              // 块哈希值
    uint64 model_hash = 3;              // 模型哈希值
    repeated int32 tokens = 4;          // token ids
    uint64 phy_size = 5;                // 物理大小
    repeated uint32 server_id = 6;      // 副本所在服务器
}

message UploadKvBlockMeta {
    uint64 token_hash = 1;              // 块哈希值
    uint64 model_hash = 2;              // 模型哈希值
    repeated int32 tokens = 3;          // token ids
    uint64 phy_size = 4;                // 物理大小
    uint64 kv_ref = 5;                  // 引用计数
}

// 本地单个 block 的引用计数
message LocalBlockCount {
    uint64 block_id = 1;            // 块 ID
    uint64 count = 2;               // 引用计数（定期同步时为增量计数，启动同步时为全量计数）
}

// 更新kvmeta的操作方式（创建、删除副本时）
message UpdateKvOp {
    uint64 block_id = 1;            // 块 ID
    uint32 operation = 2;           // server_id的修改方式（1为增加，2为删除）
    uint32 server_id = 3;           // server_id
}

// 1. GetKvMeta - 获取副本列表
message GetKvMetaRequest {
    MetaServer meta_server = 1; // 本地节点的元数据服务器信息
    DataServer data_server = 2; // 本地节点的数据服务器信息
}

message GetKvMetaResponse {
    repeated KvBlockMeta meta = 1;      // 副本信息列表
    repeated MetaServer meta_server = 2; // 目标节点已知的元数据服务器信息
    repeated DataServer data_server = 3; // 目标节点已知的数据服务器信息
    repeated LocalBlockCount local_counts = 4; // 本地所有 block 的全量计数
}

// 2. UpdateKvMeta - 更新kvcache元数据
message UpdateKvMetaRequest {
    repeated KvBlockMeta meta = 1;             // 本地新的kvcache元数据
    repeated LocalBlockCount local_counts = 2; // 本地所有 block 的增量计数
    repeated UpdateKvOp update_op= 3;          // 创建、删除KV Cache副本
    uint64 update_time = 4;                    // 本地快照的时间戳
}

message UpdateKvMetaResponse {
    repeated MetaServer meta_server = 1; // 目标节点已知的元数据服务器信息
    repeated DataServer data_server = 2; // 目标节点已知的数据服务器信息
}




service KvMeta2Data {
    rpc GetLocalKvMeta(GetLocalKvMetaRequest) returns (GetLocalKvMetaResponse);
    rpc UploadKvMeta(UploadKvMetaRequest) returns (UploadKvMetaResponse);
}


// 1.数据服务器向元数据服务器发送全部kvblockmeta
message GetLocalKvMetaRequest {
    repeated UploadKvBlockMeta kvmeta = 1; 
}

message GetLocalKvMetaResponse {
    bool success = 1;
}

// 2.数据服务器向元数据服务器上传本地新增kvcache元数据
message UploadKvMetaRequest {
    repeated UploadKvBlockMeta kvmeta = 1; 
}

message UploadKvMetaResponse {
    bool success = 1;
}

