syntax = "proto3";

package meta2data;

service Meta2Data {
    rpc AllocBlock(AllocBlockRequest) returns (AllocBlockResponse);
    rpc FreeBlock(FreeBlockRequest) returns (FreeBlockResponse);
    rpc CopyBlock(CopyBlockRequest) returns (CopyBlockResponse);
//    rpc CreateReplica(CreateReplicaRequest) returns (CreateReplicaResponse);
//    rpc UpdateReplica(UpdateReplicaRequest) returns (UpdateReplicaResponse);
//    rpc DeleteReplica(DeleteReplicaRequest) returns (DeleteReplicaResponse);
//    rpc MigrateReplica(MigrateReplicaRequest) returns (MigrateReplicaResponse);
}

message AllocBlockRequest {
    uint64 num = 1;
}

message AllocBlockResponse {
    repeated int64 bids = 1;
}

message FreeBlockRequest {
    int64 bid = 1;
}

message FreeBlockResponse {}

message CopyBlockRequest {
    int64 src_bid = 1;
    int64 dst_bid = 2;
    string addr = 3;
}

message CopyBlockResponse {}

//message CreateReplicaRequest {
//    int64 bid = 1;
//    string ip_addr = 2;
//}
//
//message CreateReplicaResponse {
//    int64 bid = 1;
//}
//
//message Copy {
//    string ip_addr = 1;
//    int64 bid = 2;
//    bool ownership = 3;
//    uint64 version = 4;
//}
//
//message UpdateReplicaRequest {
//    int64 bid = 1;
//    repeated Copy copies = 2;
//}
//
//message UpdateReplicaResponse {}
//
//message DeleteReplicaRequest {
//    int64 bid = 1;
//}
//
//message DeleteReplicaResponse {}
//
//message MigrateReplicaRequest {
//    int64 src_bid = 1;
//    int64 dst_bid = 2;
//    string ip_addr = 3;
//}
//
//message MigrateReplicaResponse {}
